FROM python:3.8.1-slim-buster

ARG ENCRYPT_KEY

WORKDIR /home/djangoRestReactShop
RUN apt-get update && \
    apt-get install --no-install-recommends -y gcc linux-libc-dev libc6-dg && \
    pip3 install --upgrade pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt /home/telegram-stickers/
RUN pip3 install --no-cache -r requirements.txt
COPY deploy/stage/telegram-stickers-stage.json.gpg telegram_stickers/ /home/telegram-stickers/
RUN gpg --quiet --batch --yes --decrypt --passphrase="$ENCRYPT_KEY" \
    --output telegram-stickers-stage.json telegram-stickers-stage.json.gpg
CMD uvicorn telegram_stickers.asgi:application --host 0.0.0.0 --port 80 --workers 4
EXPOSE 80
