# Generated by Django 3.1.1 on 2020-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=64, upload_to='images', verbose_name='Image'),
        ),
    ]
