# Generated by Django 2.2.6 on 2019-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191013_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='asdas', max_length=64, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=64, upload_to='products/', verbose_name='Image'),
        ),
    ]
