# Generated by Django 2.2.6 on 2019-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=64, upload_to='static/images', verbose_name='Image'),
        ),
    ]
