# Generated by Django 2.2.6 on 2019-10-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.IntegerField(choices=[(1, 'Phone'), (2, 'Tablet')], max_length=64, verbose_name='Categories'),
        ),
    ]
