# Generated by Django 2.2.6 on 2019-10-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20191011_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.IntegerField(choices=[(0, 'Phone'), (1, 'Tablet')], verbose_name='Categories'),
        ),
    ]
