# Generated by Django 2.2.6 on 2019-10-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20191011_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
    ]
