# Generated by Django 2.2.6 on 2019-10-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Title'),
        ),
    ]
