# Generated by Django 2.2.6 on 2019-10-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20191015_2155'),
        ('orderItem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersItems',
            new_name='OrderItem',
        ),
    ]
