# Generated by Django 2.2.6 on 2019-10-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191015_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[(0, 'Added to cart'), (1, 'Finished')], max_length=2, verbose_name='Order state'),
        ),
    ]
