# Generated by Django 2.2.6 on 2019-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191015_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, 'Added to cart'), (1, 'Finished')], verbose_name='Order state'),
        ),
    ]
